@startuml
title Car Model 
class Car{
    -manufacture:string
    -Model:string
    -year:int
    +color:string
    +activateWipers(speed):void
    +openSunRoof():void
    +playRadio(station):void
    +drive():void
    +stop():void
}
@enduml